# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x05proto\"<\n\nCredential\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"3\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04nama\x18\x03 \x01(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1a\n\tUserToken\x12\r\n\x05token\x18\x01 \x01(\t\"$\n\x06IsAuth\x12\x0e\n\x06isAuth\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x32\xa1\x01\n\x04\x41uth\x12/\n\x0bGetAuthByID\x12\r.proto.UserID\x1a\x0f.proto.UserData\"\x00\x12\x35\n\x0eGetAuthByToken\x12\x10.proto.UserToken\x1a\x0f.proto.UserData\"\x00\x12\x31\n\x0b\x43heckIfAuth\x12\x11.proto.Credential\x1a\r.proto.IsAuth\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREDENTIAL']._serialized_start=21
  _globals['_CREDENTIAL']._serialized_end=81
  _globals['_USERDATA']._serialized_start=83
  _globals['_USERDATA']._serialized_end=134
  _globals['_USERID']._serialized_start=136
  _globals['_USERID']._serialized_end=156
  _globals['_USERTOKEN']._serialized_start=158
  _globals['_USERTOKEN']._serialized_end=184
  _globals['_ISAUTH']._serialized_start=186
  _globals['_ISAUTH']._serialized_end=222
  _globals['_AUTH']._serialized_start=225
  _globals['_AUTH']._serialized_end=386
# @@protoc_insertion_point(module_scope)
