# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: produk.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cproduk.proto\x12\x05proto\"\x1a\n\x0cPriceRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\rPriceResponse\x12\r\n\x05price\x18\x01 \x01(\x05\x32y\n\x06Produk\x12\x35\n\x08GetPrice\x12\x13.proto.PriceRequest\x1a\x14.proto.PriceResponse\x12\x38\n\tGetPrices\x12\x13.proto.PriceRequest\x1a\x14.proto.PriceResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'produk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRICEREQUEST']._serialized_start=23
  _globals['_PRICEREQUEST']._serialized_end=49
  _globals['_PRICERESPONSE']._serialized_start=51
  _globals['_PRICERESPONSE']._serialized_end=81
  _globals['_PRODUK']._serialized_start=83
  _globals['_PRODUK']._serialized_end=204
# @@protoc_insertion_point(module_scope)
