# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cart_pb2 as cart__pb2


class CartStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClearCart = channel.unary_unary(
                '/proto.Cart/ClearCart',
                request_serializer=cart__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=cart__pb2.ClearCartResponse.FromString,
                )
        self.GetTotal = channel.unary_unary(
                '/proto.Cart/GetTotal',
                request_serializer=cart__pb2.GetTotalRequest.SerializeToString,
                response_deserializer=cart__pb2.GetTotalResponse.FromString,
                )


class CartServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CartServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=cart__pb2.ClearCartRequest.FromString,
                    response_serializer=cart__pb2.ClearCartResponse.SerializeToString,
            ),
            'GetTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotal,
                    request_deserializer=cart__pb2.GetTotalRequest.FromString,
                    response_serializer=cart__pb2.GetTotalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Cart', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cart(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Cart/ClearCart',
            cart__pb2.ClearCartRequest.SerializeToString,
            cart__pb2.ClearCartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Cart/GetTotal',
            cart__pb2.GetTotalRequest.SerializeToString,
            cart__pb2.GetTotalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
