# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import produk_pb2 as produk__pb2


class ProdukStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrice = channel.unary_unary(
                '/proto.Produk/GetPrice',
                request_serializer=produk__pb2.PriceRequest.SerializeToString,
                response_deserializer=produk__pb2.PriceResponse.FromString,
                )
        self.GetPrices = channel.stream_unary(
                '/proto.Produk/GetPrices',
                request_serializer=produk__pb2.PriceRequest.SerializeToString,
                response_deserializer=produk__pb2.PriceResponse.FromString,
                )


class ProdukServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrices(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProdukServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrice,
                    request_deserializer=produk__pb2.PriceRequest.FromString,
                    response_serializer=produk__pb2.PriceResponse.SerializeToString,
            ),
            'GetPrices': grpc.stream_unary_rpc_method_handler(
                    servicer.GetPrices,
                    request_deserializer=produk__pb2.PriceRequest.FromString,
                    response_serializer=produk__pb2.PriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Produk', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Produk(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Produk/GetPrice',
            produk__pb2.PriceRequest.SerializeToString,
            produk__pb2.PriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPrices(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/proto.Produk/GetPrices',
            produk__pb2.PriceRequest.SerializeToString,
            produk__pb2.PriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
