# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import auth_pb2 as auth__pb2


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAuthByID = channel.unary_unary(
                '/proto.Auth/GetAuthByID',
                request_serializer=auth__pb2.UserID.SerializeToString,
                response_deserializer=auth__pb2.UserData.FromString,
                )
        self.GetAuthByToken = channel.unary_unary(
                '/proto.Auth/GetAuthByToken',
                request_serializer=auth__pb2.UserToken.SerializeToString,
                response_deserializer=auth__pb2.UserData.FromString,
                )
        self.CheckIfAuth = channel.unary_unary(
                '/proto.Auth/CheckIfAuth',
                request_serializer=auth__pb2.Credential.SerializeToString,
                response_deserializer=auth__pb2.IsAuth.FromString,
                )


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAuthByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthByToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIfAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAuthByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthByID,
                    request_deserializer=auth__pb2.UserID.FromString,
                    response_serializer=auth__pb2.UserData.SerializeToString,
            ),
            'GetAuthByToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthByToken,
                    request_deserializer=auth__pb2.UserToken.FromString,
                    response_serializer=auth__pb2.UserData.SerializeToString,
            ),
            'CheckIfAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIfAuth,
                    request_deserializer=auth__pb2.Credential.FromString,
                    response_serializer=auth__pb2.IsAuth.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAuthByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Auth/GetAuthByID',
            auth__pb2.UserID.SerializeToString,
            auth__pb2.UserData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAuthByToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Auth/GetAuthByToken',
            auth__pb2.UserToken.SerializeToString,
            auth__pb2.UserData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckIfAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Auth/CheckIfAuth',
            auth__pb2.Credential.SerializeToString,
            auth__pb2.IsAuth.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
