# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kategori.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekategori.proto\x12\x05proto\"\x1d\n\x0fKategoriRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x10KategoriResponse\x12\x10\n\x08kategori\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t2L\n\x08Kategori\x12@\n\x0bGetKategori\x12\x16.proto.KategoriRequest\x1a\x17.proto.KategoriResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kategori_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KATEGORIREQUEST']._serialized_start=25
  _globals['_KATEGORIREQUEST']._serialized_end=54
  _globals['_KATEGORIRESPONSE']._serialized_start=56
  _globals['_KATEGORIRESPONSE']._serialized_end=106
  _globals['_KATEGORI']._serialized_start=108
  _globals['_KATEGORI']._serialized_end=184
# @@protoc_insertion_point(module_scope)
