# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\x12\x05proto\"#\n\x10\x43learCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"$\n\x11\x43learCartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x0fGetTotalRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"!\n\x10GetTotalResponse\x12\r\n\x05total\x18\x01 \x01(\x02\x32\x87\x01\n\x04\x43\x61rt\x12@\n\tClearCart\x12\x17.proto.ClearCartRequest\x1a\x18.proto.ClearCartResponse\"\x00\x12=\n\x08GetTotal\x12\x16.proto.GetTotalRequest\x1a\x17.proto.GetTotalResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLEARCARTREQUEST']._serialized_start=21
  _globals['_CLEARCARTREQUEST']._serialized_end=56
  _globals['_CLEARCARTRESPONSE']._serialized_start=58
  _globals['_CLEARCARTRESPONSE']._serialized_end=94
  _globals['_GETTOTALREQUEST']._serialized_start=96
  _globals['_GETTOTALREQUEST']._serialized_end=130
  _globals['_GETTOTALRESPONSE']._serialized_start=132
  _globals['_GETTOTALRESPONSE']._serialized_end=165
  _globals['_CART']._serialized_start=168
  _globals['_CART']._serialized_end=303
# @@protoc_insertion_point(module_scope)
